# Generated by Django 4.2.5 on 2023-09-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='chislo',
            new_name='number',
        ),
    ]
