# Generated by Django 4.2.5 on 2023-09-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_chislo_game_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='game',
        ),
    ]
